### ISSUE TITLE
rndc [-b source-address] unusable on NAT servers

### ISSUE THREAD

**Issue by abien** [plesk/ext-slave-dns-manager#20]
Since the introduction of -b in https://github.com/plesk/ext-slave-dns-manager/commit/f97e5b4bdea8183113afc5026f21d380b0edb452 this extension no longer functions in NAT Setup. The NAT Server will not be able to bind to the external address. The error can be seen in below screenshot.

(address not available)

![chrome_2017-05-16_13-26-56](https://cloud.githubusercontent.com/assets/254409/26103800/6ce915fe-3a3b-11e7-86a5-c45dac4a80e6.png)

I noticed this on my scaleway VM. The functionality of -b should be optional.

**Comment by ayamshanov** [comment]
I think in file plib/library/IpAddress.php at line 22 (https://github.com/plesk/ext-slave-dns-manager/blob/master/plib/library/IpAddress.php#L22) should be 
`$ipAddress = (string)$address->ip_address;`
instead of 
`$ipAddress = (string)$address->public_ip_address ?: (string)$address->ip_address;`

I replaced this string in file `/usr/local/psa/admin/plib/modules/slave-dns-manager/library/IpAddress.php` on my AWS test-server and this resolve the problem. You can try this as workaround.

**Comment by Neurosis404** [comment]
Same here. Need a fix very soon, all my domain registrations get canceled right now because my slaves don't know the new zones that I'm adding.

**Comment by wverboom** [comment]
How can i install this fix? Just copy those new files over the existing ones?

**Comment by ayamshanov** [comment]
Please be careful, this is only pull request from my side but it is not approved into repository and not fully tested inside QA.

Please wait update of extension from Extension Catalog.

**Comment by xgin** [comment]
The fix looks good to me.
Let me know if you have applied and it works for your environment.

**Comment by wverboom** [comment]
xgin: just copy these files over the original ones? thats is?

**Comment by xgin** [comment]
Fixed in version 1.9.0 (29 May 2017)
